# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ lenka-rss ]
  pull_request:
    branches: [ lenka-rss ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Install Quasar cli
      run: npm install -g @quasar/cli
    - name: Quasar build
      run: quasar build
    - run: npm test
